trigger: [push]

resources:
  repositories:
    - repository: scancode-action
      type: github
      name:  aboutcode-org/scancode-action
      ref: main
      endpoint:github-https://github.com/praseeda-10

jobs:
  -job: scan_codebase
  displayName: 'Scan codebase with ScanCode.io'
  steps:
    -template: azure-pipelines/templates/scancode-template.yml@scancode-action
        parameters:
          pipelines: 'scan_codebase'
          outputFormats: 'json xlsx spdx cyclonedx'