name: "ScanCode action"
description: "Run ScanCode.io pipelines in your workflows"
inputs:
  pipeline-name:
    description: "Name of the pipeline"
    required: true
    default: "scan_codebase"
  project-name:
    description: "Name of the project"
    required: true
    default: "scancode-action"
  python-version:
    description: "Python version"
    default: "3.11"
  output-formats:
    description: "Output formats"
    default: "json xlsx spdx cyclonedx"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install and setup ScanCode.io
      shell: bash
      run: |
        pip install scancodeio
        echo "SECRET_KEY=abcd" > /etc/scancodeio/.env
        cat /etc/scancodeio/.env
        SCANCODEIO_DB_ENGINE="django.db.backends.sqlite3" SCANCODEIO_DB_NAME="sqlite3.db" scanpipe migrate
    - name: Create project and run the ${{ inputs.pipeline-name }} pipeline
      shell: bash
      run: SCANCODEIO_DB_ENGINE="django.db.backends.sqlite3" SCANCODEIO_DB_NAME="sqlite3.db" scanpipe create-project ${{ inputs.project-name }}
        --input-url https://github.com/${GITHUB_REPOSITORY}/archive/${GITHUB_REF}.zip
        --pipeline ${{ inputs.pipeline-name }}
        --execute
    - name: Generate outputs
      shell: bash
      run: SCANCODEIO_DB_ENGINE="django.db.backends.sqlite3" SCANCODEIO_DB_NAME="sqlite3.db" scanpipe output --project ${{ inputs.project-name }} --format ${{ inputs.output-formats }} --no-color
    - name: Upload outputs
      uses: actions/upload-artifact@v4
      with:
        name: scan-outputs
        path: ${{ github.action_path }}/**/output/*
