on: [push]

jobs:
  scan-codebase:
    runs-on: ubuntu-24.04
    name: Analyze a Docker image
    steps:
      - uses: nexB/scancode-action@alpha
        with:
          pipelines: "analyze_docker_image"
          input-urls:
            https://github.com/aboutcode-org/scancode.io-tutorial/releases/download/sample-images/30-alpine-nickolashkraus-staticbox-latest.tar
