on: [push]

jobs:
  scan-codebase:
    runs-on: ubuntu-24.04
    name: Analyze a Docker image
    steps:
      - name: Get the action.yml and scripts from the current branch
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            action.yml
            scripts/
          sparse-checkout-cone-mode: false

      - uses: ./
        with:
          pipelines: "analyze_docker_image"
          input-urls:
            https://github.com/aboutcode-org/scancode.io-tutorial/releases/download/sample-images/30-alpine-nickolashkraus-staticbox-latest.tar
