on: [push]

jobs:
  scan-codebase:
    runs-on: ubuntu-24.04
    name: Scan codebase and find vulnerabilities
    steps:
      - name: Get the action.yml from the current branch
        uses: actions/checkout@v4
        with:
          sparse-checkout: action.yml
          sparse-checkout-cone-mode: false

      - uses: actions/checkout@v4
        with:
          path: scancode-inputs
      - uses: ./
        with:
          pipelines: "scan_codebase,find_vulnerabilities"
          scancodeio-repo-branch: "main"
          check-compliance: true
          compliance-fail-on-vulnerabilities: true
        env:
          VULNERABLECODE_URL: https://public.vulnerablecode.io/
