on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  scan-codebase:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    name: Scan codebase and find vulnerabilities
    steps:
      - name: Get the action.yml from the current branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          sparse-checkout: |
            action.yml
            scripts/scanpipe.sh
          sparse-checkout-cone-mode: false
          persist-credentials: false

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          path: scancode-inputs
          persist-credentials: false

      - uses: ./
        with:
          pipelines: "scan_codebase,find_vulnerabilities"
          check-compliance: true
          compliance-fail-on-vulnerabilities: true
        env:
          VULNERABLECODE_URL: https://public.vulnerablecode.io/
