on: [push]

jobs:
  scan-codebase:
    runs-on: ubuntu-latest
    name: Scan codebase with ScanCode.io
    steps:
      - uses: nexB/scancode-action@alpha
        with:
          pipeline-name: "scan_codebase"
