on: [push]

jobs:
  scan-codebase:
    runs-on: ubuntu-latest
    name: Scan codebase with ScanCode.io
    steps:
      - uses: actions/checkout@v4
        with:
          path: scancode-inputs
      - uses: nexB/scancode-action@alpha
        with:
          pipelines: "scan_codebase,find_vulnerabilities"
        env:
          VULNERABLECODE_URL: https://public.vulnerablecode.io/
