on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    name: ScanCode-action
    steps:
      - uses: nexB/scancode-action@alpha
        with:
          project-name: "test"
          output-formats: "json"
