on: [push]

jobs:
  scan-codebase:
    runs-on: ubuntu-24.04
    name: Run Android D2D
    steps:
      - name: Get the action.yml from the current branch
        uses: actions/checkout@v4
        with:
          sparse-checkout: action.yml
          sparse-checkout-cone-mode: false

      - uses: ./
        with:
          scancodeio-repo-branch: "main"
          scancodeio-extras: "android_analysis"
          pipelines: "android_d2d"
          input-urls:
            https://github.com/aboutcode-org/scancode.io/raw/main/scanpipe/tests/data/d2d/jars/from-flume-ng-node-1.9.0.zip#from
            https://github.com/aboutcode-org/scancode.io/raw/main/scanpipe/tests/data/d2d/jars/to-flume-ng-node-1.9.0.zip#to