on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  scan-codebase:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    name: Run Android D2D
    steps:
      - name: Get the action.yml from the current branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          sparse-checkout: action.yml
          sparse-checkout-cone-mode: false
          persist-credentials: false

# scancodeio-extras: "android_analysis" not available with the Docker image for now
#      - uses: ./
#        with:
#          scancodeio-extras: "android_analysis"
#          pipelines: "android_d2d"
#          input-urls:
#            https://github.com/aboutcode-org/scancode.io/raw/main/scanpipe/tests/data/d2d/jars/from-flume-ng-node-1.9.0.zip#from
#            https://github.com/aboutcode-org/scancode.io/raw/main/scanpipe/tests/data/d2d/jars/to-flume-ng-node-1.9.0.zip#to
