on: [push]

jobs:
  scan-codebase:
    runs-on: ubuntu-24.04
    name: Scan codebase and check for compliance issues
    steps:
      - uses: actions/checkout@v4
      - name: Run the action from current branch
        uses: ./action.yml
        with:
          inputs-path: ./
          pipelines: "scan_codebase"
          check-compliance: true
          compliance-fail-level: "WARNING"
