on: [push]

jobs:
  scan-codebase:
    runs-on: ubuntu-24.04
    name: Scan codebase and check for compliance issues
    steps:
      - name: Get the action.yml and scripts from the current branch
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            action.yml
            scripts/
          sparse-checkout-cone-mode: false

      - uses: actions/checkout@v4
        with:
          path: scancode-inputs
      - uses: ./
        with:
          pipelines: "scan_codebase"
          check-compliance: true
          compliance-fail-level: "WARNING"
