on: [push]

jobs:
  scan-codebase:
    runs-on: ubuntu-latest
    name: Scan package with ScanCode.io
    steps:
      - name: Download repository archive to scancode-inputs/ directory
        run: |
          wget --directory-prefix=scancode-inputs https://github.com/${GITHUB_REPOSITORY}/archive/${GITHUB_REF}.zip
      - uses: nexB/scancode-action@alpha
        with:
          pipelines: "scan_package"
