on: [push]

jobs:
  scan-codebase:
    runs-on: ubuntu-24.04
    name: Scan codebase and check for compliance issues
    steps:
      - uses: actions/checkout@v4
        with:
          path: scancode-inputs
      - uses: nexB/scancode-action@alpha
        with:
          pipelines: "scan_codebase"
          check-compliance: true
