on: [push]

jobs:
  scan-codebase:
    runs-on: ubuntu-22.04
    name: Scan codebase with ScanCode.io
    steps:
      - uses: actions/checkout@v4
        with:
          path: scancode-inputs
      - uses: nexB/scancode-action@4-d2d-examples
        with:
          pipelines:
            scan_codebase
            find_vulnerabilities
        env:
          VULNERABLECODE_URL: https://public.vulnerablecode.io/
